/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as AttacksRouteImport } from './routes/attacks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TargetsIndexRouteImport } from './routes/targets/index'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as ScansNewRouteImport } from './routes/scans/new'
import { Route as ScansScanIdRouteImport } from './routes/scans/$scanId'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AttacksRoute = AttacksRouteImport.update({
  id: '/attacks',
  path: '/attacks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsIndexRoute = TargetsIndexRouteImport.update({
  id: '/targets/',
  path: '/targets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansNewRoute = ScansNewRouteImport.update({
  id: '/scans/new',
  path: '/scans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/scans/$scanId',
  path: '/scans/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/playground': typeof PlaygroundRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/new': typeof ScansNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/targets/': typeof TargetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/playground': typeof PlaygroundRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/new': typeof ScansNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/targets': typeof TargetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/playground': typeof PlaygroundRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/new': typeof ScansNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/targets/': typeof TargetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attacks'
    | '/playground'
    | '/scans/$scanId'
    | '/scans/new'
    | '/settings/api-keys'
    | '/targets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attacks'
    | '/playground'
    | '/scans/$scanId'
    | '/scans/new'
    | '/settings/api-keys'
    | '/targets'
  id:
    | '__root__'
    | '/'
    | '/attacks'
    | '/playground'
    | '/scans/$scanId'
    | '/scans/new'
    | '/settings/api-keys'
    | '/targets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttacksRoute: typeof AttacksRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ScansScanIdRoute: typeof ScansScanIdRoute
  ScansNewRoute: typeof ScansNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  TargetsIndexRoute: typeof TargetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attacks': {
      id: '/attacks'
      path: '/attacks'
      fullPath: '/attacks'
      preLoaderRoute: typeof AttacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/': {
      id: '/targets/'
      path: '/targets'
      fullPath: '/targets/'
      preLoaderRoute: typeof TargetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/new': {
      id: '/scans/new'
      path: '/scans/new'
      fullPath: '/scans/new'
      preLoaderRoute: typeof ScansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttacksRoute: AttacksRoute,
  PlaygroundRoute: PlaygroundRoute,
  ScansScanIdRoute: ScansScanIdRoute,
  ScansNewRoute: ScansNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  TargetsIndexRoute: TargetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
